version: '3.8'

services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - D:/postgrestPJ/api/app:/usr/src/app
    working_dir: /usr/src/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5432:5432
    volumes:
      - D:/postgrestPJ/api/DB:/var/lib/postgresql/data