const userCRUD = require('../controllers/controllers')
//const productCRUD = require('../controllers/controllers_product')
const express = require('express')
// const {apiRoute} = express.Router()
//const upload_user = require('../public/javascript/imageUploader')
//const upload_product = require('../public/javascript/productImgUploader')
module.exports = app => {
    // app.use('/user',express.Router().get('/',(req,res)=>{
    //     console.log(req.method,"===>",res.statusMessage)    
    //    return res.send("this is from endpoint /user")
    // }))
    app.use('/user',express.Router().get('/',userCRUD.ListAllUser)
    .get('/:id',userCRUD.ListUserById)
    .post('/',userCRUD.AddUser)
    .put('/:id',userCRUD.UpdateUser)
    .delete('/:id',userCRUD.DeleteUser))
    app.use('/user2',express.Router().get('/',(req,res)=>{res.send("this is from endpoint /user2")}))
    // app.use('/product', express.Router()
    // .get('/',productCRUD.GetProduct)
    // .get('/:id',productCRUD.GetProductById)
    // .post('/new_product',productCRUD.AddProduct)
    // .put('/:id',productCRUD.UpdateProduct)
    // )
}
